### PR TITLE
feat: create `tag-name`; create `ban-name`; revert analyzer version

### LINKED ISSUE #717: [BUG] Dependency resolution fails, seemingly because it depends on `analyzer 3.x` which is too high
dart 2.10.2
dart-code-metrics from the master branch. Notice the package from pub.dev is good.

error message is like:

```
Because every version of flutter_test from sdk depends on test_api 0.4.8 and test >=1.20.0 depends on test_api 0.4.9, flutter_test from sdk is incompatible with test >=1.20.0.
And because every version of common_dart from path depends on test ^1.16.5, if flutter_test from sdk and common_dart from path then test >=1.16.5 <1.20.0.
And because test >=1.17.10 <1.20.0 depends on analyzer >=1.0.0 <3.0.0 and test >=1.16.6 <1.17.10 depends on analyzer ^1.0.0, if flutter_test from sdk and common_dart from path then analyzer >=1.0.0 <3.0.0 or test >=1.16.5 <1.16.6.
And because test >=1.16.1 <1.16.6 depends on analyzer >=0.39.5 <2.0.0 and every version of dart_code_metrics from path depends on analyzer >=3.3.0 <3.4.0, one of flutter_test from sdk or common_dart from path or dart_code_metrics from path must be false.
And because vision_utils_dart depends on common_dart_core from path which depends on dart_code_metrics from path, flutter_test from sdk is incompatible with common_dart from path.
So, because vision_utils_dart depends on both common_dart from path and flutter_test from sdk, version solving failed.
```

/cc @dkrutskikh @incendial

### PR DESCRIPTION
**Pull request by fzyzcjy**
### What is the purpose of this pull request? (put an "X" next to an item)

[ ] Documentation update
[ ] Bug fix
[x] New rule
[ ] Changes an existing rule
[ ] Add autofixing to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

### What changes did you make? (Give an overview)
#715 
#708
close #717

### CODE REVIEW

**Comment by incendial** [comment]
> > variableFromExternalPackage.doSomething(); // LINT
>
> This lint is expected indeed. e.g. Never use showDialog from Flutter's code. This is what this rule originally born for
>
> > s.doSomething(); // LINT
>
> This lint is also expected since users can rename it (or, ignore it) if they do not like

Yeah, but there is one case when the rule gives false positives - it's when you try to ban some of **your** methods and it also triggers on imported from an external package code. We can now add a note about this behaviour in the docs or fix it. I'm okay with any of those solutions.

**Comment by fzyzcjy** [comment]
> Yeah, but there is one case when the rule gives false positives - it's when you try to ban some of your methods and it also triggers on imported from an external package code. We can now add a note about this behaviour in the docs or fix it. I'm okay with any of those solutions.

Agree. I will add note about it.

**Comment by fzyzcjy** [comment]
Done

**Comment by incendial** [comment]
Thanks! All good for me, waiting for @dkrutskikh to take a look

**Comment by fzyzcjy** [comment]
You are welcome!

**Review by dkrutskikh — APPROVED** [review]

**Pull request merged**
