### PR TITLE
feat: add support for global rules-exclude

### PR DESCRIPTION
**Pull request by xsahil03x**
### What is the purpose of this pull request?

- [ ] Documentation update
- [ ] Bug fix
- [ ] New rule
- [ ] Changes an existing rule
- [ ] Add autofixing to a rule
- [ ] Add a CLI option
- [x] Add something to the core
- [ ] Other, please explain:

### CODE REVIEW

**Comment by xsahil03x** [comment]
@dkrutskikh @incendial can you please review?

**Comment by incendial** [comment]
@xsahil03x thank you very much! This request looks awesome 🚀🚀🚀
 
 Could you please update the changelog too and I'll merge it? Something like:
 ```md
 # Changelog
 
 ## Unreleased
 
 * Add support for global rules-exclude
 ```
 
 Also, I'll unlink the issue since we close them only when the changes are available on pub.

**Comment by xsahil03x** [comment]
Hey @incendial, just updated the Changelog. Can you also make sure these changes are also released for `meta < 1.7.0`? Maybe `*.dev-5`

**Comment by incendial** [comment]
@dkrutskikh please test the PR on a real codebase and let me know if it's ready to be merged.

**Comment by dkrutskikh** [comment]
> @dkrutskikh please test the PR on a real codebase and let me know if it's ready to be merged.

@incendial all is ok

**Review by dkrutskikh — APPROVED** [review]

**Pull request merged**
