### PR TITLE
feat: add static code diagnostic consistent-update-render-object

### PR DESCRIPTION
**Pull request by incendial**
### What is the purpose of this pull request? (put an "X" next to an item)

- [ ] Documentation update
- [ ] Bug fix
- [X] New rule
- [ ] Changes an existing rule
- [ ] Add autofixing to a rule
- [ ] Add a CLI option
- [ ] Add something to the core
- [ ] Other, please explain:

### CODE REVIEW

**Comment by incendial** [comment]
@fzyzcjy again kindly asking you to take a look 🙂

**Comment by incendial** [comment]
https://github.com/flutter/flutter/blob/4b4c876fb9e960329bd86dc143b6e6776eee8abb/packages/flutter/lib/src/cupertino/text_selection_toolbar.dart#L171 - edge case?
https://github.com/flutter/flutter/blob/b0aa50255b117dd6afd178ddae7f0c7b4a01dc11/packages/flutter/lib/src/cupertino/sliding_segmented_control.dart#L743 - edge case too?
https://github.com/flutter/flutter/blob/b0aa50255b117dd6afd178ddae7f0c7b4a01dc11/packages/flutter/lib/src/cupertino/dialog.dart#L808 - interesting, some constants?
https://github.com/flutter/flutter/blob/d72daf602de72a096b9f5c76468e95b69033412c/packages/flutter/lib/src/cupertino/slider.dart#L303 - constants too
https://github.com/flutter/flutter/blob/b0aa50255b117dd6afd178ddae7f0c7b4a01dc11/packages/flutter/lib/src/cupertino/switch.dart#L377 - same thing with state
https://github.com/flutter/flutter/blob/c150c5a03dd8f17d050521a2bd94e61d6b56f997/packages/flutter/lib/src/material/time_picker.dart#L698 - **bug?**
https://github.com/flutter/flutter/blob/082ad11422dae822c47808337e18a9d2af5734eb/packages/flutter/lib/src/material/tabs.dart#L302 - oh, that would be hard to handle
https://github.com/flutter/flutter/blob/d3bc2bbcdd814beb343719d9b7fed58b3807675f/packages/flutter/lib/src/material/range_slider.dart#L712 - also state thing
https://github.com/flutter/flutter/blob/2aa348b9407e96ffe4eca8e8f213c7984afad3f7/packages/flutter/lib/src/widgets/sliver_persistent_header.dart#L393-L394 - no update, **bug?**
https://github.com/flutter/flutter/blob/2aa348b9407e96ffe4eca8e8f213c7984afad3f7/packages/flutter/lib/src/widgets/sliver_persistent_header.dart#L413-L414 - same
https://github.com/flutter/flutter/blob/15739345da5a077bb54a403a505994bffae79783/packages/flutter/lib/src/widgets/basic.dart#L3422-L3423 - also no update, but looks like a false positive, since no fields
https://github.com/flutter/flutter/blob/15739345da5a077bb54a403a505994bffae79783/packages/flutter/lib/src/widgets/basic.dart#L3506-L3507 - same
https://github.com/flutter/flutter/blob/c58dca2a45d2c33c1f206db80519306371ee0eed/packages/flutter/lib/src/widgets/editable_text.dart#L3749 - **missing backgroundCursorColor, bug?**
https://github.com/flutter/flutter/blob/2aa348b9407e96ffe4eca8e8f213c7984afad3f7/packages/flutter/lib/src/widgets/sliver_prototype_extent_list.dart#L52 - **missing update, bug?**
https://github.com/flutter/flutter/blob/51bcdb9407211ccaf0616533fe1f9eb0e8f04fca/packages/flutter/lib/src/widgets/performance_overlay.dart#L115 - **missing few fields, bug?**
https://github.com/flutter/flutter/blob/2aa348b9407e96ffe4eca8e8f213c7984afad3f7/packages/flutter/lib/src/widgets/size_changed_layout_notifier.dart#L54-L55 - expected?
https://github.com/flutter/flutter/blob/2aa348b9407e96ffe4eca8e8f213c7984afad3f7/packages/flutter/lib/src/widgets/list_wheel_scroll_view.dart#L1069 - edge case with context?

**Comment by fzyzcjy** [comment]
Let me put a tick box to track it:

- [ ] https://github.com/flutter/flutter/blob/4b4c876fb9e960329bd86dc143b6e6776eee8abb/packages/flutter/lib/src/cupertino/text_selection_toolbar.dart#L171 - edge case?

- [ ] https://github.com/flutter/flutter/blob/b0aa50255b117dd6afd178ddae7f0c7b4a01dc11/packages/flutter/lib/src/cupertino/sliding_segmented_control.dart#L743 - edge case too?

- [ ] https://github.com/flutter/flutter/blob/b0aa50255b117dd6afd178ddae7f0c7b4a01dc11/packages/flutter/lib/src/cupertino/dialog.dart#L808 - interesting, some constants?

- [ ] https://github.com/flutter/flutter/blob/d72daf602de72a096b9f5c76468e95b69033412c/packages/flutter/lib/src/cupertino/slider.dart#L303 - constants too

- [ ] https://github.com/flutter/flutter/blob/b0aa50255b117dd6afd178ddae7f0c7b4a01dc11/packages/flutter/lib/src/cupertino/switch.dart#L377 - same thing with state

- [ ] https://github.com/flutter/flutter/blob/c150c5a03dd8f17d050521a2bd94e61d6b56f997/packages/flutter/lib/src/material/time_picker.dart#L698 - bug?

- [ ] https://github.com/flutter/flutter/blob/082ad11422dae822c47808337e18a9d2af5734eb/packages/flutter/lib/src/material/tabs.dart#L302 - oh, that would be hard to handle

- [ ] https://github.com/flutter/flutter/blob/d3bc2bbcdd814beb343719d9b7fed58b3807675f/packages/flutter/lib/src/material/range_slider.dart#L712 - also state thing

- [ ] https://github.com/flutter/flutter/blob/2aa348b9407e96ffe4eca8e8f213c7984afad3f7/packages/flutter/lib/src/widgets/sliver_persistent_header.dart#L393-L394 - no update, bug?

- [ ] https://github.com/flutter/flutter/blob/2aa348b9407e96ffe4eca8e8f213c7984afad3f7/packages/flutter/lib/src/widgets/sliver_persistent_header.dart#L413-L414 - same

- [ ] https://github.com/flutter/flutter/blob/15739345da5a077bb54a403a505994bffae79783/packages/flutter/lib/src/widgets/basic.dart#L3422-L3423 - also no update, but looks like a false positive, since no fields

- [ ] https://github.com/flutter/flutter/blob/15739345da5a077bb54a403a505994bffae79783/packages/flutter/lib/src/widgets/basic.dart#L3506-L3507 - same

- [ ] https://github.com/flutter/flutter/blob/c58dca2a45d2c33c1f206db80519306371ee0eed/packages/flutter/lib/src/widgets/editable_text.dart#L3749 - missing backgroundCursorColor, bug?

- [ ] https://github.com/flutter/flutter/blob/2aa348b9407e96ffe4eca8e8f213c7984afad3f7/packages/flutter/lib/src/widgets/sliver_prototype_extent_list.dart#L52 - missing update, bug?

- [ ] https://github.com/flutter/flutter/blob/51bcdb9407211ccaf0616533fe1f9eb0e8f04fca/packages/flutter/lib/src/widgets/performance_overlay.dart#L115 - missing few fields, bug?

- [ ] https://github.com/flutter/flutter/blob/2aa348b9407e96ffe4eca8e8f213c7984afad3f7/packages/flutter/lib/src/widgets/size_changed_layout_notifier.dart#L54-L55 - expected?

- [ ] https://github.com/flutter/flutter/blob/2aa348b9407e96ffe4eca8e8f213c7984afad3f7/packages/flutter/lib/src/widgets/list_wheel_scroll_view.dart#L1069 - edge case with context?

**Comment by fzyzcjy** [comment]
Aha this rule catches many more bugs! And they cause more problems - because the bug we caught w/ our previous lint rule only affect performance, while this rule catches *logically wrong* bugs. Great job!

So, same as before, shall I make a PR to flutter?

**Comment by incendial** [comment]
I'll check your response a bit later (I didn't list all the duplicate cases) and maybe add more links. After that, sure

**Comment by fzyzcjy** [comment]
Sure, take your time!

**Comment by fzyzcjy** [comment]
> I'll check your response a bit later (I didn't list all the duplicate cases) and maybe add more links. After that, sure

So I guess we are ready to file issues? :)

**Comment by incendial** [comment]
> > I'll check your response a bit later (I didn't list all the duplicate cases) and maybe add more links. After that, sure
> 
> So I guess we are ready to file issues? :) (Given all those git updates)

Sorry, no, I did everything easy and left this one for today 😄 (I also want to clean the rule from false-positives)

**Comment by fzyzcjy** [comment]
Sure, take your time!

**Comment by incendial** [comment]
@fzyzcjy supported most the false positives, checking the source code again

**Comment by incendial** [comment]
Edge case https://github.com/flutter/flutter/blob/f614c597022fd1fafca698f2fd824a707223c84e/packages/flutter/lib/src/widgets/framework.dart#L4760 ?

**Comment by incendial** [comment]
Left several edge cases not supported (assertions, a super call, method calls, constants) and looks like it's okay to have them.

**Comment by fzyzcjy** [comment]
> Edge case https://github.com/flutter/flutter/blob/f614c597022fd1fafca698f2fd824a707223c84e/packages/flutter/lib/src/widgets/framework.dart#L4760 ?

Think so. That field is final, so no need to update

**Pull request merged**
