### PR TITLE
fix: no-magic-number not working in array of widgets

### PR DESCRIPTION
**Pull request by HFabi**
### What is the purpose of this pull request? (put an "X" next to an item)

[ ] Documentation update
[x ] Bug fix
[ ] New rule
[ ] Changes an existing rule
[ ] Add autofixing to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

https://github.com/dart-code-checker/dart-code-metrics/issues/515

### What changes did you make? (Give an overview)
I changed the _isNotInsideCollectionLiteral method in the no-magic-number rule to only check the nearest ancestor and not the whole ast.

### CODE REVIEW

**Comment by dkrutskikh** [comment]
@HFabi first of all, thank you for contribution. Please update test cases at `test/src/analyzers/lint_analyzer/rules/rules_list/no_magic_number/no_magic_number_test.dart` and documentation `website/docs/rules/common/no-magic-number.md`

**Comment by HFabi** [comment]
I added a test caste which is very similar to the reported bug. The documentation is already correct and there are no changes necessary.

**Comment by HFabi** [comment]
How can I update the changelog.md?
```Error: File "changelog.md" of the pull request: "fix: no-magic-number not working in array of widgets" not updated for the scope "repo".```

**Comment by incendial** [comment]
@HFabi to update the changelog add a new entry under the `Unreleased` section. The entry text could be the same as the PR title.

**Comment by incendial** [comment]
Could you also add `// LINT` comments in the test example file like in other example files?

**Comment by HFabi** [comment]
@incendial I updated the changelog and the test

**Review by dkrutskikh — APPROVED** [review]

**Review by incendial — APPROVED** [review]

**Comment by incendial** [comment]
@HFabi thank you very much for the contribution!

**Pull request merged**
