### PR TITLE
feat: Create new rule `tag-name`

### PR DESCRIPTION
**Pull request by fzyzcjy**
### What is the purpose of this pull request? (put an "X" next to an item)

[ ] Documentation update
[ ] Bug fix
[x] New rule
[ ] Changes an existing rule
[ ] Add autofixing to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

### What changes did you make? (Give an overview)
#713

### CODE REVIEW

**Review by incendial — APPROVED** [review]

**Comment by incendial** [comment]
@dkrutskikh please take a look too

**Comment by fzyzcjy** [comment]
👀

**Comment by fzyzcjy** [comment]
👀 👀

**Comment by fzyzcjy** [comment]
A few days have passed, so I merge them into my forked repo's master branch. Further PR happens in https://github.com/dart-code-checker/dart-code-metrics/pull/722.

**Pull request closed without merging**
