### PR TITLE
fix: support excludes and conditional imports for check-unused-code

### PR DESCRIPTION
**Pull request by incendial**
### What is the purpose of this pull request? (put an "X" next to an item)

[ ] Documentation update
[X] Bug fix
[ ] New rule
[ ] Changes an existing rule
[ ] Add autofixing to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

### CODE REVIEW

**Comment by diegoveloper** [comment]
hey, thanks for the fix @incendial , are you going to release a new version with these changes? :D

**Comment by incendial** [comment]
We need to test it first, and then sure, probably a dev.2 release.

**Comment by diegoveloper** [comment]
> We need to test it first, and then sure, probably a dev.2 release.

sounds good! I tested your branch and it worked perfectly!

**Comment by incendial** [comment]
> > We need to test it first, and then sure, probably a dev.2 release.
> 
> sounds good! I tested your branch and it worked perfectly!

I'll update the branch today to cover one specific edge-case with excludes. May I ask you to recheck the fix on your codebase afterwards?

Also really curious, did it manage to find some unused code?

**Review by dkrutskikh — APPROVED** [review]

**Pull request merged**
